### PR TITLE
use release version of babylon

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks a lot @graingert, but I made the decision to officially fold this into the typescript-eslint-parser project: https://github.com/eslint/typescript-eslint-parser/pull/342

**Comment by graingert** [comment]
@JamesHenry cool beans

**Comment by graingert** [comment]
@JamesHenry any update on https://github.com/eslint/typescript-eslint-parser/issues/335 ?

**Comment by JamesHenry** [comment]
Slow and steady 😄  I am now on the Babel team and actively working on a large babel-eslint refactor. The TS support in babel-eslint will come in time, but at the same time there will be no "huge" advantage to end users when it does. I recommend you use typescript-eslint-parser for now, and join the babel slack group if you are interested in keeping abreast of the changes.

**Comment by graingert** [comment]
> Babel team and actively working on a large babel-eslint refactor. 

hype. Is there an issue tracking that?

**Comment by JamesHenry** [comment]
https://github.com/babel/babel-eslint/pull/509

It does not have anything to do with TypeScript yet (and won't in this PR), but it has allowed me to get up to speed on babel-eslint and make it much easier to update in the future.

**Pull request closed without merging**
